// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealEstate.Api.Data;

#nullable disable

namespace RealEstate.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealEstate.Api.Domain.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LogoKey")
                        .HasColumnType("text")
                        .HasColumnName("logo_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_agencies");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_agencies_slug");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_agencies_user_id");

                    b.ToTable("agencies", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Domain.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("SeekerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seeker_id");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_conversations_owner_id");

                    b.HasIndex("SeekerId")
                        .HasDatabaseName("ix_conversations_seeker_id");

                    b.HasIndex("ListingId", "SeekerId")
                        .IsUnique()
                        .HasDatabaseName("ix_conversations_listing_id_seeker_id");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Domain.Favorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "ListingId")
                        .HasName("pk_favorites");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_favorites_listing_id");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Domain.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<decimal>("AreaM2")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("area_m2");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("integer")
                        .HasColumnName("bathrooms");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DealType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("deal_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("ExpiryReminderSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_reminder_sent_at");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<bool>("HasBalcony")
                        .HasColumnType("boolean")
                        .HasColumnName("has_balcony");

                    b.Property<bool>("HasElevator")
                        .HasColumnType("boolean")
                        .HasColumnName("has_elevator");

                    b.Property<bool>("HasParking")
                        .HasColumnType("boolean")
                        .HasColumnName("has_parking");

                    b.Property<string>("Heating")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("heating");

                    b.Property<bool>("IsFurnished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_furnished");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("ModerationNote")
                        .HasColumnType("text")
                        .HasColumnName("moderation_note");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("neighborhood");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("PhoneRevealCount")
                        .HasColumnType("integer")
                        .HasColumnName("phone_reveal_count");

                    b.Property<decimal>("PriceEur")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_eur");

                    b.Property<decimal?>("PricePerM2")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_per_m2")
                        .HasComputedColumnSql("round(price_eur / nullif(area_m2, 0), 2)", true);

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("property_type");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int?>("Rooms")
                        .HasColumnType("integer")
                        .HasColumnName("rooms");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("title");

                    b.Property<int?>("TotalFloors")
                        .HasColumnType("integer")
                        .HasColumnName("total_floors");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer")
                        .HasColumnName("year_built");

                    b.HasKey("Id")
                        .HasName("pk_listings");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_listings_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_listings_owner_id");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_listings_status_expires_at");

                    b.HasIndex("Status", "PublishedAt")
                        .HasDatabaseName("ix_listings_status_published_at");

                    b.HasIndex("Status", "DealType", "PropertyType", "City")
                        .HasDatabaseName("ix_listings_status_deal_type_property_type_city");

                    b.ToTable("listings", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Domain.ListingPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("LargeKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("large_key");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("ThumbKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumb_key");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_listing_photos");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_listing_photos_listing_id");

                    b.ToTable("listing_photos", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Domain.ListingReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_listing_reports");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_listing_reports_listing_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_listing_reports_status");

                    b.ToTable("listing_reports", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId", "SentAt")
                        .HasDatabaseName("ix_messages_conversation_id_sent_at");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Domain.SavedSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("criteria");

                    b.Property<bool>("EmailAlerts")
                        .HasColumnType("boolean")
                        .HasColumnName("email_alerts");

                    b.Property<DateTimeOffset>("LastAlertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_alerted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_searches");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_saved_searches_user_id");

                    b.ToTable("saved_searches", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Domain.Agency", b =>
                {
                    b.HasOne("RealEstate.Api.Domain.User", "User")
                        .WithOne("Agency")
                        .HasForeignKey("RealEstate.Api.Domain.Agency", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agencies_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstate.Api.Domain.Conversation", b =>
                {
                    b.HasOne("RealEstate.Api.Domain.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_listings_listing_id");

                    b.HasOne("RealEstate.Api.Domain.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_users_owner_id");

                    b.HasOne("RealEstate.Api.Domain.User", "Seeker")
                        .WithMany()
                        .HasForeignKey("SeekerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_users_seeker_id");

                    b.Navigation("Listing");

                    b.Navigation("Owner");

                    b.Navigation("Seeker");
                });

            modelBuilder.Entity("RealEstate.Api.Domain.Favorite", b =>
                {
                    b.HasOne("RealEstate.Api.Domain.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_listings_listing_id");

                    b.HasOne("RealEstate.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_users_user_id");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("RealEstate.Api.Domain.Listing", b =>
                {
                    b.HasOne("RealEstate.Api.Domain.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listings_users_owner_id");

                    b.OwnsOne("RealEstate.Api.Domain.LegalStatus", "Legal", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool?>("HasCadastreCertificate")
                                .HasColumnType("boolean")
                                .HasColumnName("legal_has_cadastre_certificate");

                            b1.Property<bool?>("HasConstructionPermit")
                                .HasColumnType("boolean")
                                .HasColumnName("legal_has_construction_permit");

                            b1.Property<string>("Legalization")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("legal_legalization");

                            b1.Property<string>("Notes")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("legal_notes");

                            b1.HasKey("ListingId");

                            b1.ToTable("listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId")
                                .HasConstraintName("fk_listings_listings_id");
                        });

                    b.Navigation("Legal")
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("RealEstate.Api.Domain.ListingPhoto", b =>
                {
                    b.HasOne("RealEstate.Api.Domain.Listing", null)
                        .WithMany("Photos")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listing_photos_listings_listing_id");
                });

            modelBuilder.Entity("RealEstate.Api.Domain.ListingReport", b =>
                {
                    b.HasOne("RealEstate.Api.Domain.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listing_reports_listings_listing_id");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("RealEstate.Api.Domain.Message", b =>
                {
                    b.HasOne("RealEstate.Api.Domain.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversation_id");
                });

            modelBuilder.Entity("RealEstate.Api.Domain.SavedSearch", b =>
                {
                    b.HasOne("RealEstate.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_searches_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstate.Api.Domain.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("RealEstate.Api.Domain.Listing", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("RealEstate.Api.Domain.User", b =>
                {
                    b.Navigation("Agency");
                });
#pragma warning restore 612, 618
        }
    }
}
